[package]
name = "doom"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"
default-run = "doom"
publish = false

[dependencies]
nightshade = { workspace = true, features = ["egui", "tracing"] }
bytemuck = "1.24.0"
bincode = "1.3"
indexmap = "2"
serde = { version = "1.0.228", features = ["derive"] }
