[workspace]
resolver = "2"
members = ["examples/*", "examples-native/*"]
exclude = ["plugins", "examples-native/web_host/leptos-site"]

[workspace.dependencies]
nightshade = "0.6.55"

# Uncomment to use local nightshade instead of crates.io version
# [patch.crates-io]
# nightshade = { path = "../nightshade/crates/nightshade" }
