[package]
name = "camera_in_camera"
description = "Drive-in theater with a secondary world rendered to a movie screen using multi-world rendering"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
nightshade = { workspace = true, features = ["egui", "tracing"] }

[package.metadata.gallery]
display_name = "Camera in Camera"
