[package]
name = "benchmark"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
rand = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nightshade = { workspace = true, features = ["egui", "tracing"] }
freecs = { git = "https://github.com/matthewjberger/freecs.git" }
rayon = "1.10"
