[package]
name = "dance"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2024"
default-run = "dance"
publish = false

[features]
openxr = ["nightshade/openxr"]

[dependencies]
nightshade = { version = "0.6.46", features = ["egui", "tracing"] }
tracing = "0.1"
