#[cfg(not(feature = "openxr"))]
pub mod camera;
pub mod dash;
pub mod exhibits;
pub mod flashlight;
#[cfg(not(feature = "openxr"))]
pub mod input;
pub mod interaction;
pub mod shooting;
pub mod targets;
pub mod ui;
#[cfg(not(feature = "openxr"))]
pub mod weapon;
#[cfg(feature = "openxr")]
pub mod xr;
