[workspace]
members = ["shared", "engine-plugin", "game-plugin"]
resolver = "2"

[workspace.dependencies]
nightshade = "0.6.46"
postcard = { version = "1.0", features = ["alloc"] }

[package]
name = "plugins-demo"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
nightshade = { workspace = true, features = ["plugin_runtime"] }
plugins-shared = { path = "shared" }
