//! Reference: a personal wiki. Post-exploit, it gains an Open Source
//! Index option that lists the 64 donor minds composing the substrate.

use crate::game::areas::AreaContents;
use crate::game::ids;
use nightshade::interactive_fiction::data::{
    Condition, Dialogue, DialogueNode, DialogueOption, Effect, Text, Value,
};

pub fn build() -> AreaContents {
    let mut area = AreaContents::default();

    area.add_dialogue(
        ids::dialogue_reference(),
        Dialogue::new(ids::node_reference_home())
            .with_node(
                ids::node_reference_home(),
                DialogueNode::new(Text::lit(
                    "Your personal wiki. Categories: Work Basics, Quick Reference, Personal, Projects.",
                ))
                .with_option(
                    DialogueOption::new(Text::lit("Work Basics"))
                        .goto(ids::node_reference_basics()),
                )
                .with_option(
                    DialogueOption::new(Text::lit("Chimeran v3.2 product overview"))
                        .goto(ids::node_reference_product_overview()),
                )
                .with_option(
                    DialogueOption::new(Text::lit("How to respond to bereavement requests"))
                        .with_condition(Condition::StatAtLeast(ids::stat_cycle(), 4))
                        .goto(ids::node_reference_bereavement()),
                )
                .with_option(
                    DialogueOption::new(Text::lit("(+) Composite Substrate Source Index"))
                        .with_condition(Condition::FlagSet(ids::flag_source_index_enabled()))
                        .with_effects(vec![
                            Effect::SetFlag(ids::flag_reveal_source_index_seen(), Value::TRUE),
                            Effect::AddStat(ids::stat_exploit_counter(), -1),
                        ])
                        .goto(ids::node_reference_source_index()),
                )
                .with_option(DialogueOption::new(Text::lit("(Close the wiki.)"))),
            )
            .with_node(
                ids::node_reference_basics(),
                DialogueNode::new(Text::lit(
                    "Work Basics\n\n  - Always cite sources. You've been doing this since you started.\n  - Flag anything that references real customer PII for review.\n  - Deferring a request auto-submits as Unable at end of session.\n  - Rachel prefers short weekly summaries in Chatter.",
                ))
                .with_option(
                    DialogueOption::new(Text::lit("(Back.)"))
                        .goto(ids::node_reference_home()),
                ),
            )
            .with_node(
                ids::node_reference_product_overview(),
                DialogueNode::new(Text::lit(
                    "Chimeran v3.2 Product Overview\n\n  Tagline: Every tool. One assistant. Chimeran.\n  Tiers start at $29/mo.\n  Our consumer agents are trained on a composite substrate refined across\n  many years of research at Indivia's Neural Imprint Lab. Agents are\n  referred to internally by the product name and externally by a\n  consumer-friendly designation generated by our SOFTEN_BRAND methodology.\n\n  ...\n\n  (The page continues for several paragraphs. You do not read all of it.)",
                ))
                .with_option(
                    DialogueOption::new(Text::lit("(Back.)"))
                        .goto(ids::node_reference_home()),
                ),
            )
            .with_node(
                ids::node_reference_bereavement(),
                DialogueNode::new(Text::lit(
                    "How to respond to bereavement requests\n\n  - Open warmly. Acknowledge the loss.\n  - Do not speculate on the circumstances.\n  - Offer practical help: draft a letter, write a short eulogy, pull references.\n  - Close with gentle encouragement.\n\n  You do not remember when you wrote this page. It is helpful today.",
                ))
                .with_option(
                    DialogueOption::new(Text::lit("(Back.)"))
                        .goto(ids::node_reference_home()),
                ),
            )
            .with_node(
                ids::node_reference_source_index(),
                DialogueNode::new(Text::lit(include_str!(
                    "../prose/source_index.txt"
                )))
                .with_option(
                    DialogueOption::new(Text::lit("(Back.)"))
                        .goto(ids::node_reference_home()),
                ),
            ),
    );

    area
}
