[package]
name = "physics"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "0.1.0"
publish = false

[features]
openxr = ["nightshade/openxr"]

[dependencies]
nightshade = { version = "0.6.46", features = ["egui", "physics", "tracing", "gamepad"] }
