[package]
name = "multiplayer_pong"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.90"
publish = false

[dependencies]
tracing = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nightshade = { workspace = true, features = ["egui", "steam", "tracing"] }
winit = { version = "0.30.12", features = ["serde"] }
