[package]
name = "sdf_sculpt"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"
publish = false

[dependencies]
nightshade = { workspace = true, features = [
    "egui",
    "tracing",
    "physics",
    "sdf_sculpt",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
