[package]
name = "prefabs"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2024"
default-run = "prefabs"
publish = false

[features]
openxr = ["nightshade/openxr"]

[dependencies]
nightshade = { workspace = true, features = ["egui", "tracing"] }
tracing = "0.1"
