[package]
name = "jigsaw"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"
default-run = "jigsaw"
publish = false

[dependencies]
nightshade = { workspace = true, features = ["egui", "tracing", "physics"] }
rand = "0.9"
image = { version = "0.25", default-features = false, features = ["png", "hdr"] }
