[package]
name = "lattice"
version = "0.1.0"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2024"
default-run = "lattice"
publish = false

[features]
openxr = ["nightshade/openxr"]

[dependencies]
nightshade = { workspace = true, features = ["egui", "tracing", "physics", "lattice"] }
